language: objective-c
matrix:
  include:
    - osx_image: xcode7.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8

git:
  submodules: false
before_install:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.10/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - curl -OlL "https://github.com/ReactiveCocoa/ReactiveCocoa/releases/download/v4.0.0-alpha.3/ReactiveCocoa.framework.zip"
  - unzip "ReactiveCocoa.framework.zip"
  - rm "ReactiveCocoa.framework.zip"

script:
  - set -o pipefail
  - carthage bootstrap --platform mac,iphonesimulator
  - xcodebuild test -scheme Rex-Mac | xcpretty -c
  - xcodebuild test -scheme Rex-iOS -sdk iphonesimulator | xcpretty -c

notifications:
  email: false
